version: '3.8'

services:
  phantaminum-bot:
    build: .
    container_name: phantaminum_bot
    restart: unless-stopped 
    environment:
      - NODE_ENV=production
    env_file:
      - .env 
    
    deploy:
      resources:
        limits:
          memory: 512M
